readme_target = "../README.md"
readme_src = "../README.erb.md"

task :default => readme_target

file readme_target => [readme_src, "../mrblib/main.rb"] do |t|
  sh "erb #{t.prerequisites[0]} > #{t.name}"
end

task :clean do
  rm_rf readme_target, verbose: true
end

task :test do
  sh "mruby test_fileutils.rb"
end
